### ISSUE TITLE
Potential problem with reference to this file?

### ISSUE THREAD

**Issue by ahernsean** [ansys/pyensight#252] opened 2023-07-26 14:15 UTC
https://github.com/ansys/pyensight/blob/3686758e46cacda57a93834c6cc2688c32dffc0c/doc/source/calc_functions.rst?plain=1#L3

Is this typo an issue?
`.. _caculator_functions:`
should be
`.. _calculator_functions:`

**Comment by randallfrank** [comment] 2023-08-01 02:12
Just FYI, it is a spelling error, but not a bug.   The same name is used with :ref:, so the links all work and the actual string is not visible, it is purely part of the sphinx build process.   We will switch to :doc:, and just remove the line, once the conversion has happened in the api wheel.

**Comment by randallfrank** [comment] 2023-08-03 12:45
This was fixed in #261 and in #10 for ansys-api-ensight .

**Closed by randallfrank** 2023-08-03 12:45 UTC
